# Generated by Django 5.1.5 on 2026-04-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatEvolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('codigo', models.IntegerField(blank=True, help_text='Código numérico usado en el Excel anterior (para migración)', null=True, verbose_name='Código (Excel)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Evolución',
                'verbose_name_plural': 'Evoluciones',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CatSeveridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('codigo', models.IntegerField(blank=True, help_text='Código numérico usado en el Excel anterior (para migración)', null=True, verbose_name='Código (Excel)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Severidad',
                'verbose_name_plural': 'Severidades',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CatSexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('codigo', models.IntegerField(blank=True, help_text='Código numérico usado en el Excel anterior (para migración)', null=True, verbose_name='Código (Excel)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Sexo',
                'verbose_name_plural': 'Sexo',
                'ordering': ['nombre'],
            },
        ),
    ]
