# Generated by Django 5.1.5 on 2026-04-01 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatCategoriaInterlocutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('codigo', models.IntegerField(blank=True, help_text='Código numérico usado en el Excel anterior', null=True, verbose_name='Código (Excel)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Categoría de interlocutor',
                'verbose_name_plural': 'Categorías de interlocutor',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CatCircunstanciaNivel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('codigo', models.IntegerField(blank=True, help_text='Código numérico usado en el Excel anterior', null=True, verbose_name='Código (Excel)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Circunstancia (Nivel 1)',
                'verbose_name_plural': 'Circunstancias (Nivel 1)',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CatMotivoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('codigo', models.IntegerField(blank=True, help_text='Código numérico usado en el Excel anterior', null=True, verbose_name='Código (Excel)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Motivo de consulta',
                'verbose_name_plural': 'Motivos de consulta',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CatSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('codigo', models.IntegerField(blank=True, help_text='Código numérico usado en el Excel anterior', null=True, verbose_name='Código (Excel)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CatSubtipoPresencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('codigo', models.IntegerField(blank=True, help_text='Código numérico usado en el Excel anterior', null=True, verbose_name='Código (Excel)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Subtipo presencial',
                'verbose_name_plural': 'Subtipos presenciales',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CatTipoAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('codigo', models.IntegerField(blank=True, help_text='Código numérico usado en el Excel anterior', null=True, verbose_name='Código (Excel)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de agente',
                'verbose_name_plural': 'Tipos de agente',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CatTipoContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('codigo', models.IntegerField(blank=True, help_text='Código numérico usado en el Excel anterior', null=True, verbose_name='Código (Excel)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de contacto',
                'verbose_name_plural': 'Tipos de contacto',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CatTipoExposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('codigo', models.IntegerField(blank=True, help_text='Código numérico usado en el Excel anterior', null=True, verbose_name='Código (Excel)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de exposición',
                'verbose_name_plural': 'Tipos de exposición',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CatTipoFrecuencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('codigo', models.IntegerField(blank=True, help_text='Código numérico usado en el Excel anterior', null=True, verbose_name='Código (Excel)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de frecuencia',
                'verbose_name_plural': 'Tipos de frecuencia',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CatTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('codigo', models.IntegerField(blank=True, help_text='Código numérico usado en el Excel anterior', null=True, verbose_name='Código (Excel)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('requiere_especificar', models.BooleanField(default=False, help_text='Si está activo, el formulario mostrará un campo de texto adicional', verbose_name='Requiere especificar')),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CatUbicacionEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('codigo', models.IntegerField(blank=True, help_text='Código numérico usado en el Excel anterior', null=True, verbose_name='Código (Excel)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Ubicación del evento',
                'verbose_name_plural': 'Ubicaciones del evento',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CatUbicacionInterlocutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('codigo', models.IntegerField(blank=True, help_text='Código numérico usado en el Excel anterior', null=True, verbose_name='Código (Excel)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Ubicación del interlocutor',
                'verbose_name_plural': 'Ubicaciones del interlocutor',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CatViaIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('codigo', models.IntegerField(blank=True, help_text='Código numérico usado en el Excel anterior', null=True, verbose_name='Código (Excel)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Vía de ingreso',
                'verbose_name_plural': 'Vías de ingreso',
                'ordering': ['codigo'],
            },
        ),
        migrations.AlterField(
            model_name='catevolucion',
            name='codigo',
            field=models.IntegerField(blank=True, help_text='Código numérico usado en el Excel anterior', null=True, verbose_name='Código (Excel)'),
        ),
        migrations.AlterField(
            model_name='catseveridad',
            name='codigo',
            field=models.IntegerField(blank=True, help_text='Código numérico usado en el Excel anterior', null=True, verbose_name='Código (Excel)'),
        ),
        migrations.AlterField(
            model_name='catsexo',
            name='codigo',
            field=models.IntegerField(blank=True, help_text='Código numérico usado en el Excel anterior', null=True, verbose_name='Código (Excel)'),
        ),
        migrations.CreateModel(
            name='CatCircunstanciaNivel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('codigo', models.IntegerField(blank=True, help_text='Código numérico usado en el Excel anterior', null=True, verbose_name='Código (Excel)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('nivel1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nivel2_opciones', to='expedientes.catcircunstancianivel1', verbose_name='Circunstancia Nivel 1')),
            ],
            options={
                'verbose_name': 'Circunstancia (Nivel 2)',
                'verbose_name_plural': 'Circunstancias (Nivel 2)',
                'ordering': ['nivel1__codigo', 'codigo'],
            },
        ),
    ]
